server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 # 过滤器工厂会在匹配的请求头上加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            # - 2020-05-11T21:50:14.929+08:00[Asia/Shanghai] # 在这个时间之后 url 才能正常访问
            # - Cookie=username,Janet # 带有此 cookie 才能访问 url
            - Header=X-Request-Id, \d+ # 请求头要有属性 X-Request-Id 并且值为整数的正则表达式
            - Query=username, \d+ # 要有参数名 username并且值还要是整数才能访问

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka